### ISSUE TITLE
Write UT for SocketInstance in chat-e2ee/service module

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#311]
Mock 'socket.io-client' library and write unit test.

**Comment by Shardul1908** [comment]
Can you assign me this issue? Would like to contribute to this project.

**Comment by Shardul1908** [comment]
@muke1908 
I am facing this error when I run 'npm run dev'
{
[1]   err: MongoAPIError: URI must include hostname, domain name, and tld
[1]       at resolveSRVRecord (/home/sharduld/open_source/node_projects/chat-e2ee/node_modules/mongodb/src/connection_string.ts:65:11)
[1]       at /home/sharduld/open_source/node_projects/chat-e2ee/node_modules/mongodb/src/mongo_client.ts:457:45
[1]       at maybeCallback (/home/sharduld/open_source/node_projects/chat-e2ee/node_modules/mongodb/src/utils.ts:449:19)
[1]       at MongoClient.connect (/home/sharduld/open_source/node_projects/chat-e2ee/node_modules/mongodb/src/mongo_client.ts:449:25)
[1]       at /home/sharduld/open_source/node_projects/chat-e2ee/backend/db/index.ts:17:18
[1]       at Generator.next (<anonymous>)
[1]       at /home/sharduld/open_source/node_projects/chat-e2ee/backend/db/index.ts:8:71
[1]       at new Promise (<anonymous>)
[1]       at __awaiter (/home/sharduld/open_source/node_projects/chat-e2ee/backend/db/index.ts:4:12)
[1]       at Object.connectDb (/home/sharduld/open_source/node_projects/chat-e2ee/backend/db/index.ts:14:45) {
[1]     [Symbol(errorLabels)]: Set(0) {}
[1]   }
[1] }
[1] MONGO DB ERROR! Using in-memory DB - Not reliable!!

I have already set up the .env according to the .env.sample in the repo. Not sure why the database is not connecting. Can you help me here?

**Comment by muke1908** [comment]
@Shardul1908 probably wrong URI (wrong format)?
You should still be able to run the app even if no mongo db.

**Comment by Shardul1908** [comment]
Ohh okay, let me try that. Why is MongoDB used then?

**Comment by muke1908** [comment]
If mongodb is not configured, it'll use inMem storage. Not ideal but you'll be able to run the app. Mongodb is configured in production

**Comment by Gui-leite233** [comment]
Hi @muke1908, this issue isn't assigned. Could I work on it? It'd be my first contribution here.
